### ISSUE TITLE
Screen flickers when tapping About

### ISSUE THREAD

**Issue by BernardoGiordano** [reworks/3DS_eBook_Reader#6]
I didn't check the code, but I think you're using hidKeysHeld() to enter the about menu rather then hidKeysDown()

**Comment by reworks-org** [comment]
Key Press' are  checked with hidKeysDown() and the about menu is a boolean toggle if a hidTouch.x and hidTouch.y are within the proper bounds.

It probably due to the event function calling that code multiple times because the stylus is still touching that position.

I changed it to a keybind instead.
